<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\Backend\BarkCloud.GrpcServer\BarkCloud.GrpcServer.csproj" />
    <ProjectReference Include="..\..\BarkCloud.TestKit\BarkCloud.TestKit.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.Core.Api" Version="2.71.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0" />
  </ItemGroup>

</Project>
