// <auto-generated />
using System;

using BarkCloud.Torrent.Persistence;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace BarkCloud.Torrent.Persistence.Migrations
{
    [DbContext(typeof(TorrentContext))]
    partial class TorrentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("BarkCloud.Torrent.Domain.TorrentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Downloaded")
                        .HasColumnType("bigint");

                    b.Property<string>("InfoHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MagnetUri")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Paused")
                        .HasColumnType("boolean");

                    b.Property<double>("Progress")
                        .HasColumnType("double precision");

                    b.Property<string>("SavePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<byte[]>("TorrentFile")
                        .HasColumnType("bytea");

                    b.Property<long>("TotalSize")
                        .HasColumnType("bigint");

                    b.Property<long>("Uploaded")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Torrents");
                });

            modelBuilder.Entity("BarkCloud.Torrent.Domain.TorrentFileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TorrentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TorrentId");

                    b.ToTable("TorrentFiles");
                });

            modelBuilder.Entity("BarkCloud.Torrent.Domain.TorrentFileEntity", b =>
                {
                    b.HasOne("BarkCloud.Torrent.Domain.TorrentEntity", "Torrent")
                        .WithMany("Files")
                        .HasForeignKey("TorrentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Torrent");
                });

            modelBuilder.Entity("BarkCloud.Torrent.Domain.TorrentEntity", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
